version: '3'
services: 
  ui:
    container_name: cml-ui
    build: 
      context: ./ui
    ports: 
      - 80:80
    tty: true
    volumes:
      - ./ui:/client
    image: cml-ui-img
  backend:
    container_name: cml-backend
    build:
      context: ./backend
    ports: 
      - 5001:5001
    tty: true
    volumes:
      - ./backend:/api
    image: cml-api-img