version: '3'
services: 
  ui:
    container_name: cml-ui
    build: 
      context: ./ui
    tty: true
    volumes:
      - ./ui:/client
    image: cml-ui-img
    networks: 
      - server-network
  backend:
    container_name: cml-backend
    build:
      context: ./backend
    ports: 
      - "5001:5001"
    tty: true
    volumes:
      - ./backend:/api
    image: cml-api-img
    networks: 
      - server-network
  webserver:
    container_name: nginx-proxy
    build: 
      context: ./ui
    ports:
      - "80:80"
    depends_on:
      - backend
      - ui
    image: nginx-proxy-img
    networks: 
      - server-network

networks: 
  server-network:
    driver: bridge